application:
  url: http://exercise/tap

server:
  port: 8080
  servlet:
    context-path: /api

spring:
  jpa:
    properties:
      hibernate.show_sql: false
      hibernate:format_sql: false
      hibernate.jdbc.lob.non_contextual_creation: true
      hibernate.jdbc.batch_size: 1000
      hibernate.jdbc.fetch_size: 1000
      hibernate.default_batch_fetch_size: 1000
      hibernate.order_inserts: true
      hibernate.order_updates: true
      hibernate.generate_statistics: false
    open-in-view: false
    hibernate.ddl-auto: none
  datasource:
    url: jdbc:postgresql://host.docker.internal:5432/demodb
    username: admin
    password: 123456!
    driver-class-name: org.postgresql.Driver
    name: primary

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    configUrl: /v3/api-docs/swagger-config
    enabled: true
    path: /swagger-ui.html
